---
name: Scheduled
on:
  schedule:
    - cron: '42 5 * * *'
  workflow_dispatch:

jobs:
  main:
    name: "kick-off nightlies"
    runs-on: ubuntu-22.04
    permissions: write-all
    strategy:
      matrix:
        workflowName:
          - "ci.yml"
        branch:
          - "main"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ matrix.branch }}'

      - name: Execute ${{ matrix.workflowName }} on ${{ matrix.branch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run ${{ matrix.workflowName }} --ref ${{ matrix.branch }}
