---
name: Scheduled
on:
  schedule:
    - cron: '42 5 * * *'
  workflow_dispatch:

jobs:
  main:
    name: "kick-off nightlies"
    runs-on: ubuntu-22.04
    permissions: write-all
    strategy:
      matrix:
        workflowName:
          - "ci.yml"
        branch:
          - "main"
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Execute ${{ matrix.workflowName }} on ${{ matrix.branch }}
        run: |
          gh workflow run ${{ matrix.workflowName }} --ref ${{ matrix.branch }}
